[package]
name = "crypto"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
asn1 = { path = "../asn1" }
crypto-openssl-sys = { path = "../crypto-openssl-sys" }
regex = "1.11.1"
base64 = "0.22.1"
num-bigint = "0.4"
num-traits = "0.2.19"
num-integer = "0.1.46"

