[workspace]
members = [
    "core-modules/asn1",
    "core-modules/crypto",
    "core-modules/card",
    "binding-layers/asn1-jni",
    "binding-layers/asn1-ffi",
    "binding-layers/crypto-ffi",
]
resolver = "2"
[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
