[package]
name = "asn1-ffi"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "asn1_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
asn1 = { path = "../../core-modules/asn1" }
