
[package]
name = "asn1-core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
regex = "1.9"
lazy_static = "1.4"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.22.1"
asn1-rs = "0.5.2"

[target.'cfg(target_os = "macos")'.dependencies]