# SPDX-FileCopyrightText: Copyright 2026 gematik GmbH
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# *******
#
# For additional notes and disclaimer from gematik and in case of changes by gematik,
# find details in the "Readme" file.

[alias]
# Requires `cargo-llvm-cov` and the Rust component `llvm-tools-preview`.
cov = ["llvm-cov", "--locked", "--all-features"]
cov-clean = ["llvm-cov", "clean"]
cov-html = [
    "llvm-cov",
    "--locked",
    "--all-features",
    "--html",
    "--output-dir",
    "target/llvm-cov-html",
]
cov-lcov = [
    "llvm-cov",
    "--locked",
    "--all-features",
    "--lcov",
    "--output-path",
    "target/llvm-cov.lcov.info",
]
cov-json = [
    "llvm-cov",
    "--locked",
    "--all-features",
    "--json",
    "--output-path",
    "target/llvm-cov.json",
]
cov-json-branch = [
    "llvm-cov",
    "--locked",
    "--all-features",
    "--json",
    "--branch",
    "--output-path",
    "target/llvm-cov.branch.json",
]
